/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKOptions, serverURLFromOptions } from "../lib/config";
import { HTTPClient } from "../lib/http";
import { ClientSDK } from "../lib/sdks";
import { Banking } from "./banking";
import { Llm } from "./llm";
import { Pets } from "./pets";

export class SDK extends ClientSDK {
    private readonly options$: SDKOptions;

    constructor(options: SDKOptions = {}) {
        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
        });

        this.options$ = options;
        void this.options$;
    }

    private _pets?: Pets;
    get pets() {
        return (this._pets ??= new Pets(this.options$));
    }

    private _llm?: Llm;
    get llm() {
        return (this._llm ??= new Llm(this.options$));
    }

    private _banking?: Banking;
    get banking() {
        return (this._banking ??= new Banking(this.options$));
    }
}
