/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type Cat = {
    id: string;
    type: "cat";
    name: string;
    preferredFood: string;
};

/** @internal */
export namespace Cat$ {
    export type Inbound = {
        id: string;
        type: "cat";
        name: string;
        preferred_food: string;
    };

    export const inboundSchema: z.ZodType<Cat, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string(),
            type: z.literal("cat"),
            name: z.string(),
            preferred_food: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
                type: v.type,
                name: v.name,
                preferredFood: v.preferred_food,
            };
        });

    export type Outbound = {
        id: string;
        type: "cat";
        name: string;
        preferred_food: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Cat> = z
        .object({
            id: z.string(),
            type: z.literal("cat"),
            name: z.string(),
            preferredFood: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
                type: v.type,
                name: v.name,
                preferred_food: v.preferredFood,
            };
        });
}
