/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * This is the final event sent by the server before closing the stream.
 *
 * @remarks
 * Any data sent after this event is accidental and should be ignored.
 *
 */
export type ChatCompletionSentinel = {
    data: "[DONE]";
};

/** @internal */
export namespace ChatCompletionSentinel$ {
    export type Inbound = {
        data: "[DONE]";
    };

    export const inboundSchema: z.ZodType<ChatCompletionSentinel, z.ZodTypeDef, Inbound> = z
        .object({
            data: z.literal("[DONE]"),
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });

    export type Outbound = {
        data: "[DONE]";
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ChatCompletionSentinel> = z
        .object({
            data: z.literal("[DONE]"),
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });
}
