/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ChatCompletionChunk, ChatCompletionChunk$ } from "./chatcompletionchunk";
import { ChatCompletionSentinel, ChatCompletionSentinel$ } from "./chatcompletionsentinel";
import { z } from "zod";

export type ChatStream = ChatCompletionChunk | ChatCompletionSentinel;

/** @internal */
export namespace ChatStream$ {
    export type Inbound = ChatCompletionChunk$.Inbound | ChatCompletionSentinel$.Inbound;

    export type Outbound = ChatCompletionChunk$.Outbound | ChatCompletionSentinel$.Outbound;

    export const inboundSchema: z.ZodType<ChatStream, z.ZodTypeDef, Inbound> = z.union([
        ChatCompletionChunk$.inboundSchema,
        ChatCompletionSentinel$.inboundSchema,
    ]);

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ChatStream> = z.union([
        ChatCompletionChunk$.outboundSchema,
        ChatCompletionSentinel$.outboundSchema,
    ]);
}
