/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type Dog = {
    id: string;
    type: "dog";
    name: string;
    favoriteToy: string;
};

/** @internal */
export namespace Dog$ {
    export type Inbound = {
        id: string;
        type: "dog";
        name: string;
        favorite_toy: string;
    };

    export const inboundSchema: z.ZodType<Dog, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string(),
            type: z.literal("dog"),
            name: z.string(),
            favorite_toy: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
                type: v.type,
                name: v.name,
                favoriteToy: v.favorite_toy,
            };
        });

    export type Outbound = {
        id: string;
        type: "dog";
        name: string;
        favorite_toy: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Dog> = z
        .object({
            id: z.string(),
            type: z.literal("dog"),
            name: z.string(),
            favoriteToy: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
                type: v.type,
                name: v.name,
                favorite_toy: v.favoriteToy,
            };
        });
}
