/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Cat, Cat$ } from "./cat";
import { Dog, Dog$ } from "./dog";
import { z } from "zod";

export type Pet = Dog | Cat;

/** @internal */
export namespace Pet$ {
    export type Inbound = Dog$.Inbound | Cat$.Inbound;

    export type Outbound = Dog$.Outbound | Cat$.Outbound;

    export const inboundSchema: z.ZodType<Pet, z.ZodTypeDef, Inbound> = z.union([
        Dog$.inboundSchema,
        Cat$.inboundSchema,
    ]);

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Pet> = z.union([
        Dog$.outboundSchema,
        Cat$.outboundSchema,
    ]);
}
